#%RAML 0.8
---
title: Book Store API
version: 1.0
baseUri: http://localhost:5000/api/{version}


/books:
  displayName: Books Catalog
  get:
    description: Retrieve book-related informations.
    queryParameters:
      title:
        description: "The title of a book to search (it is case insensitive and doesn't need to match the whole title)"
        required: true
        minLength: 3
        type: string
        example: "Get L"
    responses:
      200:
        body:
          application/json:
            example: !include book-examples.json
  post:
    description: Add a book to database.
    body:
      application/json:
        schema: !include book-schema.json
        example: !include book-example.json
    responses:
      201:
        description: Book has been successfully created.
      409:
        description: Book already exists.

  /{id}:
    displayName: Book
    uriParameters:
      id:
        description: |
          Book Identifier
        required: true
    get:
      description: Retrieve book-related information.
      responses:
        200:
          body:
            application/json:
              example: !include book-example.json
        404:
          description: Unable to find book with that identifier.
    put:
      description: Update book information.
      body:
        application/json:
          example: !include book-partial-example.json
      responses:
        204:
          description: |
            The book has been successfully updated.
        404:
          description: Unable to find book with that identifier.
    delete:
      description: Remove book from the catalog.
      responses:
        204:
          description: |
            The book has been successfully removed.
        404:
          description: Unable to find book with that identifier.
